version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  app-node:
    depends_on:
      - dynamodb-local
    build: .
    container_name: app-node
    ports:
      - "8080:4000"
    # volumes:
    #   - $HOME/.aws/credentials:/app/.aws/credentials:ro
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'us-east-1'